name: GKE Deployment Management

on:
  push:
    branches:
      - main

jobs:
  gke:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Authorize to GCP service account
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS_JSON }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      
    - name: Update Kubectl component
      run: gcloud --quiet components update kubectl
      
    - name: Set GCloud Project and Fetch Cluster Credentials
      run: |
        gcloud container clusters get-credentials gke_molten-topic-445707-c0_us-east1_cluster-test-tests --region us-east1 --project molten-topic-445707-c0

    - name: Update Deployment Image
      run:
        kubectl set image deployment/test-deployment nginx=nginx:latest --namespace=${{ secrets.NAMESPACE }}
