name: Deploy to Kubernetes on Google Cloud

on:
  push:
    branches:
      - main # Adjust this if your default branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Google Cloud SDK
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: molten-topic-445707-c0
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      # Set up kubectl to interact with GKE
      - name: Set up kubectl
        run: |
          gcloud container clusters get-credentials cluster-test-tests \
            --region us-east1 \
            --project molten-topic-445707-c0

      # Get the deployments from the 'two' namespace
      - name: Get deployments in 'two' namespace
        run: |
          kubectl get deployments --namespace=two
