name: Update Deployment Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'  # Corrected input

    - name: Convert JSON to YAML and Set up Kubeconfig
      run: |
        mkdir -p $HOME/.kube
        
        # Convert the KUBE_CONFIG (JSON) secret into a YAML formatted file
        echo "${{ secrets.KUBE_CONFIG }}" | jq . > $HOME/.kube/config
        
        # Debugging: Print the content of the YAML Kubeconfig
        cat $HOME/.kube/config
        
        chmod 600 $HOME/.kube/config

    - name: Update Deployment Image
      run: |
        kubectl set image deployment/test-deployment nginx=nginx:latest --namespace=${{ secrets.NAMESPACE }}
