name: Update Deployment Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        kubectl-version: 'latest'

    - name: Debug Kubeconfig Secret
      run: |
        echo "${{ secrets.KUBE_CONFIG }}"

    - name: Set up Kubeconfig
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config
        chmod 600 $HOME/.kube/config

    - name: Update Deployment Image
      run: |
        kubectl set image deployment/test-deployment nginx=nginx:latest --namespace=${{ secrets.NAMESPACE }} --record
